---
- hosts: all
  become: true
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Copy local index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html