name: 'Ansible'

on:
  push

permissions:
  contents: read

# env:
#   PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - shell: bash
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H jkingdon-webserver-vm.eastus.cloudapp.azure.com > ~/.ssh/known_hosts        
          ansible-playbook -u jkingdon -i jkingdon-webserver-vm.eastus.cloudapp.azure.com, --private-key /tmp/id_rsa playbook.yml
          rm /tmp/id_rsa

      # - name: Run playbook
      #   uses: dawidd6/action-ansible-playbook@v2
      #   with:
      #     # Optional, directory where playbooks live
      #     directory: ansible
      #     # Required, playbook filepath
      #     playbook: playbook.yml
      #     # Optional, SSH private key
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     inventory: |
      #       [all]
      #       jkingdon-webserver-vm.eastus.cloudapp.azure.com                     
      #     # Optional, additional flags to pass to ansible-playbook
      #     options: |
      #       -u jkingdon
      #       -vvvvvv
